source "https://rubygems.org"
gem "jekyll", "~> 4.2.1"
gem "webrick", "~> 1.7"
gem "just-the-docs"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
